/**
 * Fragile magic. Do not touch.
 *
 * Just kidding, this file is autogenerated and changes will be overwritten on
 * the next build. To make changes, edit [library/build.js].
 */

import SlotRenderer from './utils/SlotRenderer/SlotRenderer'

// Export individual components
export {
  SlotRenderer
}

// Export as plugin
export default {
  install: function (Vue) {
    Vue.component('SlotRenderer', SlotRenderer)
  }
}

export { CcByIcon } from '../icons/CcByIcon'
export { CcHeartFilledIcon } from '../icons/CcHeartFilledIcon'
export { CcHeartIcon } from '../icons/CcHeartIcon'
export { CcLogoIcon } from '../icons/CcLogoIcon'
export { CcNcEuIcon } from '../icons/CcNcEuIcon'
export { CcNcJpIcon } from '../icons/CcNcJpIcon'
export { CcNcIcon } from '../icons/CcNcIcon'
export { CcNdIcon } from '../icons/CcNdIcon'
export { CcPdIcon } from '../icons/CcPdIcon'
export { CcPdmIcon } from '../icons/CcPdmIcon'
export { CcRemixIcon } from '../icons/CcRemixIcon'
export { CcSaIcon } from '../icons/CcSaIcon'
export { CcSamplingPlusIcon } from '../icons/CcSamplingPlusIcon'
export { CcSamplingIcon } from '../icons/CcSamplingIcon'
export { CcShareIcon } from '../icons/CcShareIcon'
export { CcZeroIcon } from '../icons/CcZeroIcon'
